apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: foo-devfile-sample-cza6-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: foo-devfile-sample-cza6-sample
    app.kubernetes.io/part-of: foo
  name: foo-devfile-sample-cza6-sample
  namespace: sbose-builds
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: foo-devfile-sample-cza6-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: foo-devfile-sample-cza6-sample
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:d9c5d664352ed2b9a2b948560af9fc7d3f63b61cb04723c193a3355b1a95f94b
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3001
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
