apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: foo-devfile-sample-cza6-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: foo-devfile-sample-cza6-sample
    app.kubernetes.io/part-of: foo
  name: foo-devfile-sample-cza6-sample
  namespace: sbose-builds
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: foo-devfile-sample-cza6-sample
    weight: 100
status: {}
