apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: foo-devfile-sample-cza6-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: foo-devfile-sample-cza6-sample
    app.kubernetes.io/part-of: foo
  name: foo-devfile-sample-cza6-sample
  namespace: sbose-builds
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: foo-devfile-sample-cza6-sample
status:
  loadBalancer: {}
