apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: foo
    appstudio.openshift.io/component: image-controller-grzh
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: image-controller-grzh
  namespace: sbose-builds
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_redhat-appstudio_image-controller
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/redhat-appstudio/image-controller
