apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: foo
    appstudio.openshift.io/component: foo-devfile-sample-cza6-sample
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: foo-devfile-sample-cza6-sample
  namespace: sbose-builds
spec:
  url: https://github.com/nodeshift-starters/devfile-sample
