apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-awew
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-awew
    app.kubernetes.io/part-of: foo
  name: dc-metro-map-awew
  namespace: sbose-builds
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: dc-metro-map-awew
status:
  loadBalancer: {}
