apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: image-controller-grzh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: image-controller-grzh
    app.kubernetes.io/part-of: foo
  name: image-controller-grzh
  namespace: sbose-builds
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: image-controller-grzh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: image-controller-grzh
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:73f9e324ea458a5f3a381e7ad794587013d9157aee985033e2d1753272ea7911
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
status: {}
