apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: image-controller-grzh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: image-controller-grzh
    app.kubernetes.io/part-of: foo
  name: image-controller-grzh
  namespace: sbose-builds
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: image-controller-grzh
status:
  loadBalancer: {}
